DROP TABLE IF EXISTS "albums";
CREATE TABLE "albums" (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS "users";

CREATE TABLE "users" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  date_joined TIMESTAMP DEFAULT now()
);

DROP TABLE IF EXISTS "reviews";

CREATE TABLE "reviews" (
  id SERIAL PRIMARY KEY,
  user_id INTEGER,
  review VARCHAR(255) NOT NULL
);

ALTER TABLE "reviews" ADD FOREIGN KEY (user_id) REFERENCES "users" ("id") ON DELETE CASCADE;
